= Alan Documentation Styles: templates styles samples
Tristano Ajmone <tajmone@gmail.com>
v1.1, December 3, 2018
include::_inc_header-attributes.adoc[]
:toclevels: 5
:doctype: book
// Sections Numbering:
:sectnums:
:sectnumlevels: 2

// =============================================================================
//                         Custom Attributes Definition
// =============================================================================
// Custom attributes shared by all docs:
include::_inc_custom-attributes.adoc[]


// *****************************************************************************
// *                                                                           *
// *                            Document Preamble                              *
// *                                                                           *
// *****************************************************************************

This document offers a comprehensive preview of the templates used for Alan documentation, offering samples of how fonts, typography, AsciiDoc elements, custom styles and syntax highlighting will be rendered and styled in the final documentation, allowing to compare quality and differences across all the supported output formats.

Some contents are format dependent and will vary according to the document's output format and the backend employed, providing additional information specific to that format and/or backend.


[WARNING]
================================================================================
This document is still under construction.
================================================================================


// *****************************************************************************
// *                                                                           *
// *                             Fonts Specimens                               *
// *                                                                           *
// *****************************************************************************

== Fonts Specimens

Specimens of the three main fonts used for base body text, verbatim text, and headings.

[subs="post_replacements,attributes"]
--
{font-speciemen1} +
{font-speciemen2} +
{font-speciemen3} +
{font-speciemen4}
--


[subs="attributes"]
----
{font-speciemen1}
{font-speciemen2}
{font-speciemen3}
{font-speciemen4}
----


[discrete]
=== {font-speciemen1}
[discrete]
=== {font-speciemen2}
[discrete]
=== {font-speciemen3}
[discrete]
=== {font-speciemen4}


// *****************************************************************************
// *                                                                           *
// *                             Basic Typography                              *
// *                                                                           *
// *****************************************************************************

// TBD!
// === Basic Typography

// ******************************************************************************
// *                                                                            *
// *                                   Lists                                    *
// *                                                                            *
// ******************************************************************************


== Lists


=== Unrdered List


.List Title
* Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro.
* De carne lumbering animata corpora quaeritis.
** Summus brains sit​​, morbo vel maleficia?
*** De apocalypsi gorger omero undead survivor dictum mauris.
*** Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium.
* Qui animated corpse, cricket bat max brucks terribilem incessu zomby.
* The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus.
** Zonbi tattered for solum oculi eorum defunctis go lum cerebro.
** Nescio brains an Undead zombies.
* Sicut malus putrid voodoo horror.
* Nigh tofth eliv ingdead.

=== Ordered List

.List Title
. Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens.
.. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams.
... Pestilentia est plague haec decaying ambulabat mortuos.
.... Putridi braindead odores kill and infect, aere implent left four dead.
.. Sicut zeder apathetic malus voodoo.
. Aenean a dolor plan et terror soulless vulnerum contagium accedunt, mortui iam vivam unlife.
. Qui tardius moveri, brid eof reanimator sed in magna copia sint terribiles undeath legionis.
.. Alii missing oculis aliorum sicut serpere crabs nostram.
... Putridi braindead odores kill and infect, aere implent left four dead.


=== Description List


Lucio :: fulci tremor est dark vivos magna.
Expansis :: creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis.
Romero :: morbo Congress amarus in auras.
Nihil :: horum sagittis tincidunt, zombie slack-jawed gelida survival portenta.
The unleashed :: virus est, et iam zombie mortui ambulabunt super terram.
Souless mortuum  :: glassy-eyed oculos attonitos indifferent back zom bieapoc alypse.
An hoc :: dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante?
Is bello :: mundi z?

=== Description List Horizontal

[horizontal]
Lucio :: fulci tremor est dark vivos magna.
Expansis :: creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis.
Romero :: morbo Congress amarus in auras.
Nihil :: horum sagittis tincidunt, zombie slack-jawed gelida survival portenta.
The unleashed :: virus est, et iam zombie mortui ambulabunt super terram.
Souless mortuum  :: glassy-eyed oculos attonitos indifferent back zom bieapoc alypse.
An hoc :: dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante?
Is bello :: mundi z?


=== Q&A List

[qanda]
Clairvius Narcisse, an ante?::
	The unleashed virus est, et iam zombie mortui ambulabunt super terram.
Is bello mundi z?::
	Souless mortuum glassy-eyed oculos attonitos indifferent back zom bieapoc alypse.






// ******************************************************************************
// *                                                                            *
// *                               Block Elements                               *
// *                                                                            *
// ******************************************************************************

== Block Elements




=== Example

[example]
============================================================================
Lucibus ibi medio generis amore, post sibi, puellae Ophiusiaque aera incerti
nuda. Quos et potero inpune iam. Amissa aetas! Sis *cultro* spissus rostro
aliquemque pio fugit, suum in Iovis, circumdata curru non, et spectantur
incognita carchesia
============================================================================


=== Listing

[listing]
--------------------------------------------
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc.

Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem.
--------------------------------------------


=== Literal


[literal]
............................................
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc.

Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem.
............................................


=== Source

[source]
--------------------------------------------
For i=1 To 10
  Print "Hello World!"
Next
--------------------------------------------


=== Quotations

____
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc.

Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem.

________
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc.

Post iacentem praescia neci audire fausto revellit aequo reflectitur et

____________
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc.

Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem.
____________
________
____


// *****************************************************************************
// *                                                                           *
// *                               Admonitions                                 *
// *                                                                           *
// *****************************************************************************

== Admonitions


=== Note

[NOTE]
================================================================================
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc. Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem. Quaesitique ferarum praestantior inter tunc uterque depresso an ego partim
volatu. Invita undis dei nec bibat.
================================================================================


=== Tip

[TIP]
================================================================================
Qui flere et propior umbra senectus moriturus scelus primus, de magis culpetne
utque retinens: longa cogeris Bacchus. Obruta urbe tandemque ausi utque
vastum, bracchiaque Europam mora murmur. Dulce voce in quoque, sub est nullaque,
siccantem adverso!
================================================================================


=== Warning

[WARNING]
================================================================================
Lorem markdownum rerum: est, in quod iam in. Incaluit vacuus ignibus, probetne
et hoc. Post iacentem praescia neci audire fausto revellit aequo reflectitur et
opem. Quaesitique ferarum praestantior inter tunc uterque depresso an ego partim
volatu. Invita undis dei nec bibat.
================================================================================


=== Caution

[CAUTION]
================================================================================
Qui flere et propior umbra senectus moriturus scelus primus, de magis culpetne
utque retinens: longa cogeris Bacchus. Obruta urbe tandemque ausi utque
vastum, bracchiaque Europam mora murmur. Dulce voce in quoque, sub est nullaque,
siccantem adverso!
================================================================================


=== Important

[IMPORTANT]
================================================================================
Qui flere et propior umbra senectus moriturus scelus primus, de magis culpetne
utque retinens: longa cogeris Bacchus. Obruta urbe tandemque ausi utque
vastum, bracchiaque Europam mora murmur. Dulce voce in quoque, sub est nullaque,
siccantem adverso!
================================================================================

// *****************************************************************************
// *                                                                           *
// *                                  Tables                                   *
// *                                                                           *
// *****************************************************************************

== Tables

include::_table_symbols-repl.adoc[]




// EOF //
