= Typography in Alan Documentation
Tristano Ajmone <tajmone@gmail.com>
v2.0, October 07, 2018
include::_inc_header-attributes.adoc[]
// Sections Numbering:
:sectnums:
:sectnumlevels: 2

// =============================================================================
//                         Custom Attributes Definition
// =============================================================================
// Custom attributes shared by all docs:
include::_inc_custom-attributes.adoc[]

// *****************************************************************************
// *                                                                           *
// *                            Document Preamble                              *
// *                                                                           *
// *****************************************************************************

This document is for previewing how fonts and typography in general will be rendered and styled in the final documentation, and for comparing quality and differences across all the supported output formats.

Some contents are format dependent and will vary according to the document's output format and the backend employed, providing additional information specific to that format and/or backend.

Currently, we are still in the process to choose the fonts that will be used in the final documents.


// *****************************************************************************
// *                                                                           *
// *                     Fonts Specimens & Styles Checks                       *
// *                                                                           *
// *****************************************************************************

== Fonts Specimens

Specimens of the three main fonts used for base body text, verbatim text, and headings.

[subs="post_replacements,attributes"]
--
{font-speciemen1} +
{font-speciemen2} +
{font-speciemen3} +
{font-speciemen4}
--


[subs="attributes"]
----
{font-speciemen1}
{font-speciemen2}
{font-speciemen3}
{font-speciemen4}
----


[discrete]
=== {font-speciemen1}
[discrete]
=== {font-speciemen2}
[discrete]
=== {font-speciemen3}
[discrete]
=== {font-speciemen4}



== Font Styles Availability Checks

:styles-test: pass:quotes[*bold*, _italic_ and *_bold+italic_*]

Now we need to check that every font is also available in {styles-test} style.

In heading fonts:

[discrete]
== Heading: {styles-test}

And in monospace fonts too: `{styles-test}`.

[subs="attributes,quotes,post_replacements"]
........................
Verbatim: {styles-test}.
........................


// ******************************************************************************
// *                                                                            *
// *                         Fonts Combination Preview                          *
// *                                                                            *
// ******************************************************************************

== Fonts Combination Preview

This section offers a preview of how the different fonts look like together.
// >>> http://fillerama.io
Shh! Knights, I bid you welcome to your new home. Let us ride to Camelot!
I don't want to talk to you no more, you empty-headed animal food trough water!
I fart in your general direction!
Your mother was a hamster and your father smelt of elderberries!
Now leave before I am forced to taunt you a second time!
// <<< http://fillerama.io

[source,alan]
--------------------
include::snippets.alan[tag=short_sample]
--------------------

[discrete]
=== Text Formatting

Let's test inline styling.
Text Formatting: *bold* and _italic_, ~subscript~ and ^superscript^,
`inline code` (`*bold*`, `_italic_`, `*_bold italic_*`),
"`double`" and '`single quotes`'.
Styles with attributes: #highlighter#, [small]#small print# and [big]#big text#.
Experimental features: keystrokes kbd:[Ctrl+Shift+N].


[discrete]
=== Headings

[discrete]
== Level 1 Heading

[discrete]
=== Level 2 Heading

[discrete]
==== Level 3 Heading

[discrete]
===== Level 4 Heading

[discrete]
====== Level 5 Heading


[discrete]
=== Monty Python and the Holy Grail

Courtesy of http://fillerama.io/[fillerama^].

1. We want a shrubbery!!
2. You don't vote for kings.
3. Well, how'd you become king, then?

____
Listen. Strange women lying in ponds distributing swords is no basis for a system of government.
Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony.
And this isn't my nose. This is a false one.
____


[discrete]
=== Miscellanea

Horizontal rule:

'''

// *****************************************************************************
// *                                                                           *
// *                             Ligatures Tests                               *
// *                                                                           *
// *****************************************************************************

== Ligatures Tests

Here we test if ligatures are being supported by the current backend and font.


=== Code Ligatures

Some fonts support source code related ligatures.
We'll test these code related ligatures using a test file taken from Nikita Prokopov's
https://github.com/tonsky/FiraCode[Fira Code^] project.


First we'll test for ligatures inside a source code block.
Here ligatures support could depend on the monospaced font, the backend or the syntax highligher (which may or may not filter contents of the block).

include::ligatures_test.adoc[tag=code_ligatures_source]


And now we'll carry out the test (part of it) in an example block, for here a different font is being used which may support code related ligatures.
The example block below has not special substitutions settings.

include::ligatures_test.adoc[tag=code_ligatures_example]

// ******************************************************************************
// *                                                                            *
// *                              Text Replacement                              *
// *                                                                            *
// ******************************************************************************

== Special Charachters

=== Text Replacements

The following table is used for checking that default Asciidoctor textual symbols replacement works fine.


include::_table_symbols-repl.adoc[]



// EOF //
