= Typography in Alan Documentation
Tristano Ajmone <tajmone@gmail.com>
v1.1, September 18, 2018: Typography styling previews
:version-label: v
:authorinitials: T.J.A.
// =====================
// HTML Default Settings
// =====================
:toolchain: pass:r[Asciidoctor's native HTML5]
// =====================
// PDF Settings Override
// =====================
ifeval::["{backend}" == "docbook"]
:toolchain: asciidoctor-fopub
endif::[]
// ---------------------
:revremark: Backend: {toolchain}
:toc: left
:toclevels: 5
:doctype: book
:encoding: utf-8
:lang: en
// Misc Settings:
:experimental: true
:icons: font
:linkattrs: true

// =============================================================================
//                         Custom Attributes Definition
// =============================================================================
// Some attributes for custom substitution of multiple occurences of same text.

:fopub: https://github.com/asciidoctor/asciidoctor-fopub[asciidoctor-fopub^]
:Highlight: http://www.andre-simon.de/[Highlight^]

// *****************************************************************************
// *                                                                           *
// *                            Document Preamble                              *
// *                                                                           *
// *****************************************************************************

This document is for previewing how fonts and typography in general will be rendered and styled in the final documentation, and for comparing quality and differences across all the supported output formats.

Some contents are format dependent and will vary according to the document's output format and the backend employed, providing additional information specific to that format and/or backend.

Currently, we are still in the process to choose the fonts that will be used in the final documents.

// =====================
// HTML Backend Warning:
// =====================
// Warning about use of native Asciidoctor theme and missing custom styles...
ifeval::["{backend}" == "html5"]
include::_inc_html-warning.adoc[]
endif::[]


== Ligatures Tests

Here we test if ligatures are being supported by the current backend and font.


=== Code Ligatures

Some fonts support source code related ligatures.
We'll test these code related ligatures using a test file taken from Nikita Prokopov's
https://github.com/tonsky/FiraCode[Fira Code^] project.


First we'll test for ligatures inside a source code block.
Here ligatures support could depend on the monospaced font, the backend or the syntax highligher (which may or may not filter contents of the block).

include::ligatures_test.adoc[tag=code_ligatures_source]


And now we'll carry out the test (part of it) in an example block, for here a different font is being used which may support code related ligatures.
The example block below has not special substitutions settings.

include::ligatures_test.adoc[tag=code_ligatures_example]


// EOF //
