= Syntax Highlighting in Alan Documentation
Tristano Ajmone <tajmone@gmail.com>
v1.1, September 12, 2018: Code styling previews
:version-label: v
:authorinitials: T.J.A.
// =====================
// HTML Default Settings
// =====================
:toolchain: pass:r[Asciidoctor's native HTML5]
// =====================
// PDF Settings Override
// =====================
ifeval::["{backend}" == "docbook"]
:toolchain: asciidoctor-fopub
endif::[]
// ---------------------
:revremark: Backend: {toolchain}
:toc: left
:toclevels: 5
:doctype: book
:encoding: utf-8
:lang: en
// Misc Settings:
:experimental: true
:icons: font
:linkattrs: true

// =============================================================================
//                         Custom Attributes Definition
// =============================================================================
// Some attributes for custom substitution of multiple occurences of same text.

:fopub: https://github.com/asciidoctor/asciidoctor-fopub[asciidoctor-fopub^]
:Highlight: http://www.andre-simon.de/[Highlight^]

// *****************************************************************************
// *                                                                           *
// *                            Document Preamble                              *
// *                                                                           *
// *****************************************************************************

This document is for previewing how source code and other verbatim blocks will be rendered and styled in the final documentation, and for comparing quality and differences across all the supported output formats.

Some contents are format dependent and will vary according to the document's output format and the backend employed, providing additional information specific to that format and/or backend.

Currently, we're still working on implementing syntax highlighting of Alan source code in the various output formats, as different conversion backends will employ different highlighting tools.

== Syntaxes Preview

=== Alan

[source,alan]
--------------------
include::snippets.alan[tag=sample]
--------------------

=== BNF

[source,ebnf,subs="macros"]
--------------------------------------------------------------------------------
class = 'EVERY' id
            [inheritance]
            {property}
        'END' 'EVERY' [id] ['.']
--------------------------------------------------------------------------------




== The Alan Syntax

Different conversion toolchains use different tools for syntax highlighting.
For HTML format conversion, various highlighters are natively supported by Asciidoctor.
For PDF conversion, the usable highlighting tool(s) will be dictated by the third party backend employed.

In all cases, a custom Alan syntax definiton would have to be created for the highlighter tool used with each backend, as none of them ships with a native Alan definition (the sole exception being {Highlight}, which is not natively supported in any of the backends, but could be integrated into some of them).

// ==================
// HTML Backend Only:
// ==================
ifeval::["{toolchain}" == "Asciidoctor's native HTML5"]

[WARNING]
================================================================================
Currently no syntax highlighters have been integrated into the HTML conversion toolchain.
I've created an Alan language definition for André Simon's {Highlight} tool, but haven't yet got around to integrate it into the toolchain.
Although it's not among the natively supported highlighters, it should be possible to integrate it into the HTML backend.
================================================================================
endif::[]

// ===================
// FOPUB Backend Only:
// ===================
ifeval::["{toolchain}" == "asciidoctor-fopub"]

[NOTE]
================================================================================
The PDF conversion toolchain uses {fopub} to create the PDF from the DocBook version of the documents.
Asciidoc-fopub ships with an integrated syntax highlighter, called XSLHL.
================================================================================
endif::[]

////
=== Alan Syntax Elements

The following example shows all the various Alan syntax elements groups that are highlighted, and their associated colors in the chosen color scheme.
////



=== Syntax Tests

Here follow some code snippets for testing both common- and edge-cases in the language and ensure they are rendered as expected.

==== Predefined Classes and Instances

Although it's usually unnecessary to highlight with separate styling the predefined Alan classes and instances (i.e. the `hero`), it might be desirable to be able to do so in tutorials and documentation, for educational purposes.
For this reason, I've added a special highlighting group for the predefined classes, and another one for the `hero`.
Both can be optionally enabled by assigning styles to them, or just be ignored (or set to the same style as normal text) to hide them in the highlighted source.

[source,alan]
--------------------
include::snippets.alan[tag=predefined_classes]
--------------------


==== Quoted Identifiers

Although quoted identifiers shouldn't receive any special coloring in the highlighted code, the syntax definition must be made aware of them to prevent false-positive keywords matches for tokens inside quoted identifiers:

[source,alan]
--------------------------------------------------------------------------------
The 'At the Bus Stop' IsA location --> Watch out for: 'AT', 'THE' and 'STOP'!
End The.
--------------------------------------------------------------------------------

This hidden feature will be implemented differently in each syntax definition, depending on how the specific syntax highlighting engine works.

However, in the final highlighted code, quoted identifiers are shown with the same color and style as the base (normal) text, effectively hiding to the end user the difference between quoted identifiers and plain code (normal identifiers are just treated as plain code).


===== Single Quotes Escaping

To prevent breaking up syntax highlighting, quoted identifiers need to support correctly escaping single quotes inside them via `''`. Although this won't be visible in the highlighted output of the following example, examining the document's source (with formats which support it, like HTML) would allow to check that the quoted identifier was correctly parsed and tagged by the highlighter:


[source,alan]
--------------------------------------------------------------------------------
The 'Bob''s House' IsA location --> Escaped apostrophe in location name.
End The.
--------------------------------------------------------------------------------


==== Strings



==== False Positive Keywords Matches

The following snippet tests against false positive keywords in strings and quoted identifiers. This should never happen, and if it does then the Alan syntax definition for that highlighter is flawed and needs to be fixed.

[source,alan]
--------------------------------------------------------------------------------
-- Tokens in strings and quoted IDs shouldn't be highligthed as keywords...

The 'At the Bus Stop' IsA location --> Watch out for: 'AT', 'THE' and 'STOP'!
  Description
    "An old man waits for the bus here." --> 'AN', 'FOR', 'THE', 'HERE'!
End The.
--------------------------------------------------------------------------------



== BNF Syntax

Currently, BNF blocks are not being syntax highlighted but implementing a syntax definition would be very easy.


[source,ebnf]
--------------------------------------------------------------------------------
attribute_declaration = id
                      | 'NOT' id
                      | id integer
                      | id string
                      | id id
                      | id '{' values '}'
--------------------------------------------------------------------------------


[source,ebnf]
--------------------------------------------------------------------------------
forms = indefinite | definite | negative

definite = 'DEFINITE' article_or_form

indefinite = [ 'INDEFINITE' ] article_or_form

negative = 'NEGATIVE' article_or_form

article_or_form = 'ARTICLE' {statement}
                | 'FORM' {statement}
--------------------------------------------------------------------------------

// EOF //
