// *****************************************************************************
// *                                                                           *
// *                       Appendix D: Language Grammar                        *
// *                                                                           *
// *****************************************************************************
// This appendix has been proofread and is ready to go. But some issues should
// looked into later on:
// - [ ] Styling convention for inline BNF identifiers (currently in strong,
//       while actual keywords and symbols use inline-code)
// - [ ] Keywords casing (styling conventions are not definitive yet)
// - [ ] Check that the keywords list is complete (some built-in classes aren't
//       in the list)


[appendix]
= Language Grammar

== Description

In this manual, the Alan language is defined using a BNF-form, which you can see in most descriptions.
The grammar is a set of rules defining what constructs are legal in the source for an Alan program.
Below follows a brief explanation on how to interpret these rules by using some short examples.
For details on the actual rules, refer to the content of <<Language Reference>>.

The ((BNF)) form divides the rules for structure of the input source by describing it in smaller parts, which may in turn be defined by other rules.
For example, a rule might say that an *ADVENTURE* (in this case an Alan program) consists of options, declarations and a start section.
This grammar rule would look like:

(((BNF, rules of, adventure)))
[source,bnf]
--------------------------------------------------------------------------------
adventure = [options] {declaration} start_section
--------------------------------------------------------------------------------

Each item that is an identifier (`options`, `declaration`, etc.), is a construct that in turn is defined by other rules, possibly elsewhere in the manual.

The equal sign (`=`) may be read as "`consists of`" or "`is defined as`".
Optional parts are surrounded by square brackets (`[` and `]`).
Parts that may be repeated are enclosed in curly braces (`{` and `}`).

// @NOTE: This looked much nicer in the HTML output, but not in PDF:

////
PROBLEM: In PDF output it looks hugly: the example frame is square and horrible,
         if you add a title it ends up inside the frame, and most of all it adds
         huge space between left- and right-handside of list elements!

		 If I can fix these problems in the XSL template, I should use this instead
		 of the listing block.

===========================
[horizontal]
=   :: -> {nbsp}is defined as

[ ] :: -> {nbsp}optional

{ } :: -> {nbsp}zero or more times
===========================
////

// FIMXE: Apply some custom styling to this block:

.........................
=  : 'is defined as'

[] : 'optional'

{} : 'zero or more times'
.........................

So the rule might be read as "`an adventure consists of *options* which are optional, zero or more *declarations* and a *start_section*`".

If the item to the left of the equal sign may be defined in multiple ways, the alternatives are divided by a vertical bar (`|`).
For example:

[source,bnf]
--------------------------------------------------------------------------------
declaration = messages
            | class
            | instance
            | verb
            | rule
            | synonyms
            | syntax
            | verb
            | event
            | addition
--------------------------------------------------------------------------------

This definition says that a *declaration* might be messages, a class definition, an instance declaration, etc.

The basic components of the language are reserved words and symbols.
These are represented in the rules by quoted strings of characters.
These are not defined elsewhere, but should instead be written as indicated.
Character case is not significant.

[source,bnf]
--------------------------------------------------------------------------------
random_expression = 'RANDOM' 'IN' expression
--------------------------------------------------------------------------------

// @NOTE: Should replace "CAN be followed by" with "MUST be followed by"?

The reserved words `Random` and `In` can be followed by an expression (which, to make sense, must refer to a `container` instance) to form a *random_expression* (which in itself is an expression).

== Keywords

The following is a complete list of all keywords in the Alan language.
Note that they can still be used as identifiers in a source file if the rules described in <<_words_identifiers_and_names>> are followed.
Basically this means that if you surround them by single quotes they can be used as identifiers in your source code anyway.
This might be especially important if you want to use any of these words as words the player might want to input, such as part of a name for an item.

// -----------------------------------------------------------------------------
//                  Table 5. List of Alan Language’s Keywords
// -----------------------------------------------------------------------------
// For maintaiance conveniance, we'll use a CVS Table here: it can be easily
// updated (if the need arises) and it could allow to control the number of columns
// on a per-format basis, via custom attributes.
// Keywords are cased following the styling conventions adopted in the document.

// @TODO:
//   - [ ] Check why 'actor' and 'location' are present but some of the other
//         built-in clases aren't: 'thing', 'object',
//   - [ ] The casing convention for some keywords hasn't yet been discussed:
//         - [ ] Should pseudo attributes like 'container', 'on', 'off', 'opaque'
//               etc be all lowercase (like built-in classes)?
//


[[table-of-keywords]]
.List of Alan Keywords
[format=csv,cols="5*m"]
|======================
include::manual_keywords.csv[]
|======================


[NOTE]
================================================================================
Although the Alan language is case-insensitive, the keywords in the above list are cased according to the styling conventions adopted in this document, for the sake of consistency and to provide an intuitive association between keywords and their role in the language.
================================================================================

// EOF //
