// ******************************************************************************
// *                                                                            *
// *                           4. Lexical Definitions                           *
// *                                                                            *
// ******************************************************************************


= Lexical Definitions


== Comments

Comments may be placed anywhere in the Alan source.
A comment starts with double hyphens (`--`) and extends to the end of the line.

[source,alan]
--------------------------------------------------------------------------------
-- This is a comment
--------------------------------------------------------------------------------



== Words, Identifiers and Names

// @IMPROVE @thoni56: Accented Letters in Identifiers.
//   Might be worth mentioning that letters also include letters with accents,
//   diacritics, etc., which are supported by the encoding set for the adventure.
//   This is an important topic for users authoring in languages other than English
//   which use special letters, as they'd naturally use them in identifiers too.
//   The whole topic of the different encodings supported by Alan in source files,
//   compiler switches, etc., is not covered at all in the Manual, and can lead
//   to confusion and problems. Some important questions to address:
//
//      * How do encoding settings affect the range of usable chars in identifiers?
//      * Which are the usable characters in identifiers?
//
//   The BNF rule and the text below mention "letter", but the term is rather
//   generic as it could mean many different things in different contexts -- e.g.
//   in RegEx it could be just Ascii letters, or any letter in the Unicode range.

An identifier is a word in the Alan source, which is used as a reference to a construct, such as an instance.
Identifiers (((identifier, lexical definition))) may only be composed of letters, digits and underscores.
The first character must be a letter.

(((BNF, rules of, identifier)))
[source,bnf]
--------------------------------------------------------------------------------
identifier = letter {letter | digit | underscore}
--------------------------------------------------------------------------------

=== Quoted Identifiers

There is also a second kind of identifier, namely the quoted identifier.

(((BNF, rules of, quoted identifier)))
(((BNF, rules of, identifier, quoted)))
[source,bnf]
--------------------------------------------------------------------------------
id = identifier
   | quoted_identifier

quoted_identifier = quote {any_character} quote
--------------------------------------------------------------------------------

A ((quoted identifier)) starts and ends with single quotes and may contain any character (including spaces) except single quotes -- if you need to include a single quote inside a quoted identifier, you must _escape it_ by doubling it, e.g.:

// @TODO: Add xred to glossary "escaping" in above sentence ("must escape it"),
// 		  when the entry is available.

[source,alan, subs="+quotes"]
--------------------------------------------------------------------------------
The #'Bob''s House'# IsA location. -- ID will be printed as "Bob's House"
End the.
--------------------------------------------------------------------------------

When the Alan compiler encounters two consecutive single quotes inside a quoted identifier, it will treat them as if they were one single quote which is part of the identifier, and not as a the single quote _delimiter_ indicating the end of the identifier.

In the above example, the identifier will be printed as "`Bob's House`" in the actual game -- the enclosing single quote delimiters being ignored in print, and the two consecutive single quotes printed as one single quote.

Any sequence of characters enclosed within single quotes can become an identifier, except inside strings (where single quotes are treated as ordinary printable characters).


[NOTE]
================================================================================
A single-word identifier can be written within or without single quotes, indifferently (unless it's a keyword).
Therefore, `'someID'` and `someID` both refer to the same identifier in the source code.
================================================================================

=== Keywords as Identifiers

// (((stropping)))
Quoted identifiers may also be used to create an identifier out of a reserved word such as `Look`, `The`, etc.
This practice is known as _<<gloss_stropping,((stropping))>>_, and it allows the Alan compiler to distinguish between user-created identifiers and keywords in the source code, thus avoiding clashes that would lead to a compiler error.

This is useful (indeed, required), for example, in the definition of the verb '`look`':

[source,alan]
--------------------------------------------------------------------------------
Verb 'look'
  Does
    Look.
End Verb 'look'.
--------------------------------------------------------------------------------

[IMPORTANT]
================================================================================
Whenever an identifier contains an Alan keyword, it's mandatory to use a quoted identifier.
================================================================================

In the following example, the `'The Empty Room'` name needs to be enclosed within single quotes because it contains two Alan keywords (`The` and `Empty`), but there's no need to do so with the `empty_room` identifier because the word `empty` doesn't appear in isolated form (i.e. surrounded by spaces):

[source,alan]
--------------------------------------------------------------------------------
The empty_room IsA location   --> No need to stropp 'empty_room'.
  NAME 'The Empty Room'.      --> Keywords 'THE' and 'EMPTY' stropped.
End The.
--------------------------------------------------------------------------------

[NOTE]
================================================================================
Stropping occurs only when the quoted identifier contains at least one Alan keyword.
Since in Alan it's always permissible to enclose an identifier within single quotes (where `'someID'` and `someID` both refer to the same identifier), not every quoted identifier implies stropping, but stropping _always_ requires a quoted identifier.
================================================================================


=== Names Containing Multiple Words

Quoted identifiers retain their exact content.
They may contain spaces and other special characters, which make them useful as long names for locations as in:

[source,alan]
--------------------------------------------------------------------------------
The pluto IsA location Name 'At the Rim of Pluto Crater'
  Description
    ...
--------------------------------------------------------------------------------

One single-quoted identifier is used as the whole (((NAME, of locations))) name of the location to preserve editing and avoiding clashes with the reserved words `At` and `Of`.
(This could also have been avoided by quoting just those words.)

Identifiers and words retain their capitalization.
An example is:

[source,alan]
--------------------------------------------------------------------------------
The eiffel_tower Name Eiffel tower ...
--------------------------------------------------------------------------------

The first word in the name will always be printed with a capital '`E`'.
However, when comparing the word to player input and other occurrences of the same word in the source, letter casing will be ignored (i.e. comparison is case insensitive).
This means that you cannot have two words or identifiers that differ only in case, they will be the same and stored in the game data as one of the occurrences, which one is implementation dependent.


[WARNING]
================================================================================
Do _NOT_ use a single quoted identifier with spaces or special characters in them as the name for anything other than locations, as the words in names are analysed separately and are assumed to be adjectives and nouns (where it is assumed that the last is the noun).
Except for this you should only quote single words to avoid clashes with reserved words.
================================================================================


[CAUTION]
================================================================================
Any one of the occurrences of a word might define its capitalization, which one is unspecified.
This might affect the output if you use capitalization for names of locations, such as "```Name Shore of Great Sea```".
Such names can inadvertently make the game use "`Great`" for all "`great`" things in your game.
You can avoid this by using a quoted identifier for the complete name of the location.
================================================================================



Be careful when using quoted identifiers, especially if the player is supposed to use the word.
A player cannot refer in the typed input to words which are defined in the code as single words containing spaces or other special characters or separators (the only exception being underscores and dashes).

Also, remember that a player input word must start with a letter; so the player won't be able to refer to identifiers or names like "```1st```", "```'70s```", etc.

.Escaping Single Quotes Inside Quoted Identifiers
[TIP]
================================================================================
(((escaping, single quotes in quoted identifiers)))
To include a (((single quotes))) single quote as part of a quoted identifier, double it (e.g. `'Tom''s Diner'`).
Inside the adventure, it will be printed as a single quote ("`Tom's Diner`").

This technique is known as _escaping_, for it allows the Alan compiler to distinguish between the quote character as delimiters of the quoted identifier and its occurrence within the identifier as a printable character.
================================================================================


Some of the identifiers in the source of an Alan game are used by default as player words.
This is for example the case with verb names (unless a `Syntax` statement has been declared for the `Verb`) and object names (unless a `Name` clause has been used).
If these contain special characters, the player won't be able to refer to them in the typed input.



== Numbers

(((numbers, lexical definition)))
Numbers in Alan are only integers and thus may consist only of digits.

(((BNF, rules of, numbers)))
[source,bnf]
--------------------------------------------------------------------------------
number = digit {digit}
--------------------------------------------------------------------------------



== Strings

(((string, lexical definition)))
The string is the main lexical component in an Alan source.
This is how you describe the surroundings and events to the player.
Strings, therefore, are easy to enter and consist simply of a pair of double quotes surrounding any number of characters.
The text may include newline characters and thus may cover multiple lines in the source.

(((BNF, rules of, strings)))
[source,bnf]
--------------------------------------------------------------------------------
string = double_quote {any_character} double_quote
--------------------------------------------------------------------------------

When processed by the Alan compiler, any multiple spaces, newlines and tabs will be compressed to one ((("spacing, in strings"))) single space as the formatting to fit the screen is done automatically during execution of the game (except for embedded formatting information, as specified in <<Output Statements>>).
You may therefore write your strings any way you like; they will always be neatly formatted on the player's screen.
You can use special codes (see <<String Statement>> for a list) to indicate (but not precisely control) the formatting.


[WARNING]
================================================================================
As strings may contain any character, a missing double quote may lead to many seemingly strange error messages.
If the compiler points to the first word after a double quote and indicates that it has deleted a lot if IDs (identifiers), this is probably due to a missing end quote in the previous string.
================================================================================


[TIP]
================================================================================
To get a (((double quotes))) double quote within strings repeat it (``"The sailor said ""Hello!""."``).
================================================================================




== Filenames

It is possible to write one adventure using many source files, having different parts in different files, and thus giving an opportunity for some rudimentary kind of modularisation.
The method for this is the `import` statement.

(((BNF, rules of, IMPORT)))
(((BNF, rules of, filenames)))
[source,bnf]
--------------------------------------------------------------------------------
import = 'IMPORT' quoted_identifier '.'
--------------------------------------------------------------------------------

The `Import` statement requires a filename, which must be given as a quoted
identifier (see <<_words_identifiers_and_names>>).


// EOF //
