// ******************************************************************************
// *                                                                            *
// *                     Appendix A: How to Use the System                      *
// *                                                                            *
// ******************************************************************************

[appendix]
= How to Use the System

How to actually set up and use the complete Alan system depends very much on which platform, OS and in which environment you are going to use it.

If you just want to run a game, there is of course the original command line version distributed from {alan-www}.
To use this, read the relevant sections below to get a feel for how that will work.

But there are also a number of other packages that include an Alan interpreter, http://ccxvii.net/gargoyle/[Gargoyle^] and http://ccxvii.net/spatterlight/[Spatterlight^], are two, with Gargoyle at the point of writing, being the one most up to date, and also available on multiple platforms.

If you actually want to write interactive fiction using Alan you also need the compiler.
This is distributed from {alan-www} in what's called the Development Kit, or the SDK (for Software Development Kit), which includes the compiler, interpreter, a conversion program for v2 games and some examples.

Whatever option you choose, there should be more detailed instructions on how to install included with that package.
Below follows some information pertaining to the original versions from the Alan website.

== Compiling

Although there are other options, like the AlanIDE, WinAlan et al., basic use of the Alan Adventure Development System is through a traditional command line batch compiler.
This means that the actual development system is a compiler that reads text files created using any standard text editor.
To compile an adventure use the following command in a command shell:

[literal, role="shell"]
................................................................................
alan <adventure>
................................................................................

where `<adventure>` is the name of the main file containing your adventure source text.
The compiler will assume an extension of *"`.alan`"* if none is supplied.
The option `-help` will give a brief help on other options to the compiler.

The primary output from the compiler is an adventure code file *_adventure_.a3c*.

// @NOTE: "Its content will be compiled into the adventure code file"
//        maybe use "into the adventure storyfile" instead? the term is well
//        known among IF players and authors alike, whereas "code file" is
//        a bit vague.

An identifying file, *_adventure_.ifid*, is also produced.
This is a text file containing a unique identification string of your game, for bibliographical purposes; you can open it with a text editor, in case you're curious.
Its content will be compiled into the adventure code file, which makes your game identifiable by electronic means.

As long as this file exists, the same identification (IFID) will be used.
If it does not exist, a new one will automatically be generated.

// @TODO: Here we should add some guidelines regarding the use or substitution
//        of and adventure's `.ifid` file.
//
//        QUESTION: If a user has published an adventure (v1) and then updates
//        it (as it often happens with adventures that are submitted to
//        contents, which are later on updated to fix bugs and typos), should
//        the same IFID be reused, or a new one should be created?
//        What are the Babel IF guidelines regarding this?
//
//        With books ISBN, the identifier is divided into segments, so the
//        paperback and softcover edition only vary in their final segment, and
//        updated version follow a similar line, which means that the core
//        unique ID remains the same. But IFIDs are different, for they are not
//        assigned by an authority but generated via algorithms, so every new
//        IFID is unrelated to the previous one.
//
//        We should inform the reader on whether he/she should reuse the same
//        IFID in updated version of the same adventure, and whether he/she
//        should distribute the `.ifid` file with the adventure sources, and
//        advise him/her to preserve a copy of the file, and how to recover the
//        IFID from the storyfile (via an hex editor) in case the file went
//        lost.

== Compiler Switches

(((compiler switches)))
If you run the compiler from a command line you can get information about which switches it supports using the `-help` switch:

[literal, role="shell"]
................................................................................
$ alan -help
................................................................................

Here are some examples of other switches:

* `-version` shows the version of the compiler
* `-encoding` assume source files are in this encoding.
The option should be followed with one of the keywords `iso` or `utf-8`.
This is required when your source files written using an encoding which isn't Alan's default.
Many terminals and editors today use the UTF-8 encoding but historically Alan only supported the ISO-8859-1 encoding for non-ASCII characters.
Currently the Alan compiler will default to `-encoding iso` but in the near future UTF-8 will be the default encoding for Alan source files.
* `-charset` backwards compatible alias for `-encoding`
* `-verbose` print compiler version and other verbose messages
* `-warnings`, `-infos` show warning (and/or informational) messages from the compilation process
* `-import` (((including files, compiler switches))) add a directory to the search path for imported files (see <<Filenames>> for details on the `Import` statement).
This switch can be used multiple times, each adding a new directory
* `-listing` direct compiler output (error messages etc.) to a file with the same base name as the input (source) file, but with the extension *.lis*
* `-full` will produce a complete listing of the source on the screen, or if combined with the `-listing` option, in the listing file
* `-debug` include debugging information in the produced adventure files (same as using the `debug` option in the Alan source, see <<Options>>)
* `-pack` encode and compress the text data (same as using the `pack` option in the Alan source, see <<Options>>)
* `-summary` produce a summary about number of actors, size of adventure files, timing information, etc.
* `-dump` print the internal form (developers use mainly)

Giving an extra hyphen before the option reverses its meaning (where appropriate), e.g. `--warnings` means don't show warnings.
Switches may be abbreviated as long as they are unambiguous.

== Encodings and Character Sets

If you are interested in writing adventures in anything other than English, then this section is important to you.
Else you can continue to live in oblivion of the multitude of other languages that need to be supported by computer programs these days, and skip to the next section.

Alan uses a single byte character encoding known as ISO-8859-1, both internally and in game files.
This makes game files completely portable across various platforms and still able to support most of the glyphs ("`characters`") of most Western languages.
Historically though, different operating systems and environments have used different encodings for text files, so when you created Alan source code the files were encoded differently depending on the platform (Mac, DOS, Unix, Windows, ...).

There is (still) no standardized way to deduce in which encoding a text file is, so in an attempt to handle "`national characters`" in the game source (particularly in Swedish), the `-charset` option was devised.
The options is now more appropriately called `-encoding`.
Using this option an author could indicate to the compiler how to interpret, and possibly convert, the characters in the source file(s) created on another platform.

This has changed and an encoding called UTF-8 is becoming almost the standard encoding for text on many platforms, including Windows.

// @FIXME: This paragraph might add more confusion than clarification!
//         Someone with no encoding background might infer that the BOM is a
//         substitute for UTF-8 encoding. We should clarify that the BOM is
//         only available in Unicode files, and the its an optional addition to
//         UTF-8 encoding (i.e. UTF-8 + BOM). Unfortunately, the whole topic is
//         quite complex, and while we can't offer a tutorial here, we should
//         at least strive to be precise with our terminology, to make it
//         simpler for readers who will dig the topic further.
//         Adding a few external links and footnotes wouldn't hurt either!

The Alan compiler is capable of reading and converting source files in UTF-8 (which probably is the default when you create a text file these days).
You can instruct the compiler to assume UTF-8 encoding using the `-encoding utf-8` option, but if the text file is encoded using a BOM (a special, invisible marker that may be used at the beginning of UTF-8 encoded files) the Alan compiler will automatically assume that the file is encoded in UTF-8.
If there is no BOM, Alan will assume the default encoding or as instructed by the `-encoding` option.
So it is safest to always use the `-encoding` option.

This should make the creation and editing of Alan source files a more streamlined experience than before.

See <<Compiler Switches>> and <<Interpreter Switches>> for ways to control how the compiler and interpreter interpret encoding of source files and log input and output.

== Running the Adventure

To play the generated adventure the (((Arun))) Alan interpreter, *arun*, is executed with the adventure name as a parameter.
For example:

[literal, role="shell"]
................................................................................
$ arun adventure
................................................................................

No extension on the adventure name is allowed, the *.a3c* and, if applicable, *.a3r* files are inferred and found automatically from the base name.

On platforms with graphical user interfaces to which *arun* has been natively ported, you can double click on a game file to start a game, or double click on the interpreter application icon, in which case a dialogue requesting a game file will appear.

If the interpreter program is copied to a different name, it will automatically look for a game file with the same name.
Any parameters or switches will then be ignored.
For example, by copying the *arun* program to *adventure* the interpreter will, when started under the new name, directly look for the file *adventure.a3c*.
The files *adventure* and *adventure.a3c* thus make a complete game package, which is easy to start using the single command:

[literal, role="shell"]
................................................................................
$ adventure
................................................................................

== Interpreter Switches

(((interpreter, switches)))
The ((interpreter)) supports the following switches:

* `-h` print some help
* `-v` verbose mode
* `-u` use UTF-8 encoding for input and output including logs and command scripts
* `-l` log complete game transcript to a file ('`.a3t`')
* `-c` log all player commands to a file ('`.a3s`' for "`solution`")
* `-n` no Status Line
* `-p` don't break the output for paging
* `-d` print the version of interpreter and enter debug mode
* `-t[<n>]` various levels of execution trace, higher <n> gives more details
* `-i` ignore CRC and version errors in the adventure files (dangerous)
* `-r` make regression test easier (don't timestamp, page break, randomize...)
* `-version` print version of the interpreter, the version and IFID of the game, if given, and then exit

// @NOTE: What does "the version and IFID of the game, if given" mean exactly?
//     *  The IFID is always generated, unless the game was created with a old
//        version of ALAN that didn't support IFID -- but in this case we
//        should mention this, either in a footnote or a NOTE admonition!
//     *  What does the version of the game game refer to? There is no built-in
//        mechanism to specify an adventure version, is there?


Debugging support is described in <<Debugging>>.

=== Logging options

The logging options, `-l` and `-c`, will each create a new file with a name that is the combination of the game name, a time stamp and the appropriate extension in the current directory, and write the log in it.
The options can be used simultaneously and will then create two files with differing extensions for the two types of logs.
For example

[literal,role="shell"]
................................................................................
$ arun -c adventure
................................................................................

This will give you a file named `adventure<timestamp>.a3s` which will contain all commands the player entered.
It may later be used as the so called "`solution file`" which can be followed manually to "`replay`" that session, or even used as a command script that can be feed to the interpreter using

[example,role="gametranscript"]
================================================================================
&gt; _@adventure<datestamp>.a3s_
================================================================================

On the other hand, using

[literal, role="shell"]
................................................................................
$ arun -l adventure
................................................................................

will log the complete game transcript to a file named `adventure<timestamp>.a3t`.
This option can be useful when collecting information from playtesters to analyse their progress, e.g. to improve the game.


[TIP]
================================================================================
When you're gathering feedback from beta testers, the timestamp will help collecting many such files in the same directory for analysis.
You can avoid the timestamp in filenames via the `-r` switch, e.g. to simplify scripting; but beware that doing so will overwrite the same file at each run.
================================================================================



[WARNING]
================================================================================
Some interpreters, particularly the Glk-based ones, will have their own file naming conventions, and may therefore not abide to these standardised extensions for command scripts or transcripts.
================================================================================


// EOF //
